
create table usera(
    id serial primary key,
    name varchar(50) not null
);

create table userb(
    id integer primary key generated by default as identity,
    name varchar(50) not null
);

create table user4
(
    id   integer generated by default as identity primary key,
    name varchar
);

create table user3
(
    id   integer generated always as identity primary key,
    name varchar
);

create table users2
(
    id   integer generated always as identity (start with 100
        increment by 2
        ),
    name  text not null,
    email text not null
);

select gen_random_uuid();

select uuid_generate_v4 ()as uuid;

create extension if not exists "uuid-ossp";


create table users5
(
    id   uuid primary key default uuid_generate_v4(),
--     id2 uuid default uuid_generate_v4() primary key,
    name text not null,
    email text not null
);

create sequence users5_id_seq;
drop sequence users5_id_seq;

select nextval('users5_id_seq');

create table user6
(
    id   integer primary key default nextval('users5_id_seq'),
    name text not null,
    email text not null
);