-- clase 04 1;26

CREATE TABLE CLIENTES
(
    ID             INT PRIMARY KEY IDENTITY (1,1),
    NOMBRE         NVARCHAR(50)  NOT NULL,
    APELLIDO       NVARCHAR(50)  NOT NULL,
    EMAIL          NVARCHAR(100) NOT NULL UNIQUE,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE()
)

-- Código de clase 04
CREATE DATABASE UNIV

CREATE LOGIN RAMON WITH PASSWORD = 'ramon'

USE UNIV CREATE USER RAMON FOR LOGIN RAMON

USE UNIV
GRANT SELECT ON SCHEMA::dbo TO RAMON

USE UNIV
GRANT DELETE, UPDATE, INSERT ON SCHEMA::dbo TO RAMON

CREATE TABLE ESTUDIANTES
(
    ID_ESTD   INT IDENTITY (1,1) PRIMARY KEY,
    NOMBRE    VARCHAR(50),
    APELLIDOS VARCHAR(50),
    CORREO    VARCHAR(30)
)

INSERT INTO ESTUDIANTES(NOMBRE, APELLIDOS, CORREO)
VALUES ('PEDRO', 'LUZ', 'CORREO@PEDRO')
INSERT INTO ESTUDIANTES(NOMBRE, APELLIDOS, CORREO)
VALUES ('RAMON', 'MAR', 'LUZ@RAMON')

UPDATE ESTUDIANTES
SET APELLIDOS='RUIZ'
WHERE ID_ESTD = 4

DELETE
FROM ESTUDIANTES
WHERE ID_ESTD = 2

SELECT *
FROM ESTUDIANTES;

 --GRANT SELECT ON
 sp_renamedb 'UNIV','UNIVERSAL';
