-- SUBSCONSULTAS
-- TOTAL DE VENTAS POR VENDEDOR
SELECT SUM(F.TOTAL) FROM Facturas F
WHERE F.IDEMPLEADO = (SELECT ID FROM EMPLEADO WHERE ID = 1)


SELECT SUM(F.TOTAL) FROM Facturas F
WHERE F.IDEMPLEADO = 1

-- TOTAL DE VENTAS REALIZADAS POR 1 VENDEDOR  POR MES
SELECT SUM(F.TOTAL) FROM Facturas F
WHERE F.IDEMPLEADO = (
    SELECT ID FROM EMPLEADO WHERE NOMBRE = 'Juan' AND MONTH(F.FECHA_FACTURA) = 6
    )

-- INFORMA ANUAL
SELECT YEAR(F.FECHA_FACTURA) ,
       E.NOMBRE AS VENDEDOR,
       SUM(F.TOTAL) AS TOTAL_VENTAS_ANUAL
FROM Facturas F
JOIN dbo.EMPLEADO E on F.IDEMPLEADO = E.ID
GROUP BY YEAR(F.FECHA_FACTURA), E.NOMBRE

-- REPORTES CUATRIMESTRALES
SELECT
    YEAR(F.FECHA_FACTURA),
       CASE
           WHEN MONTH(F.FECHA_FACTURA) BETWEEN 1 AND 4 THEN '1er Cuatrimestre'
           WHEN MONTH(F.FECHA_FACTURA) BETWEEN 5 AND 8  THEN '2do Cuatrimestre'
           WHEN MONTH(F.FECHA_FACTURA) BETWEEN 9 AND 12  THEN '3er Cuatrimestre'
       END AS CUATRIMESTRE,
     E.NOMBRE AS VENDEDOR,
     SUM(F.TOTAL) AS TOTAL_VENTAS_CUATRIMESTRAL
FROM Facturas F
    JOIN dbo.EMPLEADO E on F.IDEMPLEADO = E.ID
GROUP BY YEAR(F.FECHA_FACTURA), E.NOMBRE,
            CASE
                WHEN MONTH(F.FECHA_FACTURA) BETWEEN 1 AND 4 THEN '1er Cuatrimestre'
                WHEN MONTH(F.FECHA_FACTURA) BETWEEN 5 AND 8  THEN '2do Cuatrimestre'
                WHEN MONTH(F.FECHA_FACTURA) BETWEEN 9 AND 12  THEN '3er Cuatrimestre'
            END;
